sudo: false
language: node_js
node_js:
  - "10"
if: tag IS blank
script: make ci
before_install: git fetch --unshallow
jobs:
  include:
    - if: type != pull_request AND branch = master
      stage: Publish to NPM
      script: .travis/after_success.sh
