sudo: false
language: node_js
if: tag IS blank
node_js:
  - 8.9
  - 9
script: ./.travis-script.sh
before_install: git fetch --unshallow
jobs:
  include:
    - if: type != pull_request AND branch = master
      stage: Publish to NPM
      script: .travis/after_success.sh
